### ISSUE TITLE
这个申请内存大小原来是3100，运行过程会导致内存不够，但是改的多了就可以了，这个3100是默认的吗？

### ISSUE THREAD

**Issue by fortunerains** [RT-Thread-packages/TJpgDec#5]
![image](https://user-images.githubusercontent.com/24492495/142157981-f739234a-ab33-4412-913b-476290090e7c.png)

**Comment by fortunerains** [comment]
![image](https://user-images.githubusercontent.com/24492495/142159667-b58d33fd-bfd4-415a-9f53-b4e1ed68b8d1.png)

**Comment by mysterywolf** [comment]
如果你是用这个example的话，你可以用一个小一点的图片试试，这个只是一个example，图片质量越高，需要的内存可能越大

**Comment by fortunerains** [comment]
> 如果你是用这个example的话，你可以用一个小一点的图片试试，这个只是一个example，图片质量越高，需要的内存可能越大

确实用的example，

**Comment by fortunerains** [comment]
> 如果你是用这个example的话，你可以用一个小一点的图片试试，这个只是一个example，图片质量越高，需要的内存可能越大

我刚刚用了一个32*32的小图但是也是会报内存错误

**Comment by mysterywolf** [comment]
emmm 那你提交一个pr吧&nbsp; 内存搞大一点&nbsp; 能打开你需求的图象



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月17日(周三) 晚上8:28
收件人: ***@***.***&gt;;
抄送: "Man, Jianting ***@***.******@***.***&gt;;
主题: Re: [RT-Thread-packages/TJpgDec] 这个申请内存大小原来是3100，运行过程会导致内存不够，但是改的多了就可以了，这个3100是默认的吗？ (Issue #5)




  
如果你是用这个example的话，你可以用一个小一点的图片试试，这个只是一个example，图片质量越高，需要的内存可能越大
  
我刚刚用了一个32*32的小图但是也是会报内存错误

**Comment by fortunerains** [comment]
> emmm 那你提交一个pr吧&nbsp; 内存搞大一点&nbsp; 能打开你需求的图象
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年11月17日(周三) 晚上8:28 收件人: ***@***.***&gt;; 抄送: "Man, Jianting ***@***.******@***.***&gt;; 主题: Re: [RT-Thread-packages/TJpgDec] 这个申请内存大小原来是3100，运行过程会导致内存不够，但是改的多了就可以了，这个3100是默认的吗？ (Issue #5) 如果你是用这个example的话，你可以用一个小一点的图片试试，这个只是一个example，图片质量越高，需要的内存可能越大 我刚刚用了一个32*32的小图但是也是会报内存错误 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我再研究下

**Comment by fortunerains** [comment]
目前这个值不能固定，这个值是取决于不同分辨率的jpg文件的

**Comment by mysterywolf** [comment]
是的 调大一点 至少小图片就可以正确显示了
